// Mock claude -p stand-in for the design_course stage. Writes a stub
// course.json into <coursesRoot>/<slug>/ that validates against CourseSchema.
// When a course-spec.json is present in the same dir it honours the
// wizard's draftStructure (so multi-lesson curricula survive into the
// realised course, used by US-108's lesson-progress slider playwright
// test); otherwise falls back to a single-lesson 'intro' stub.
//
// Spawned by defaultDesignCourseCommand() when GENERATION_MOCK === '1'.
//
// argv[2] = slug          (already validated by assertSafeSlug before spawn)
// argv[3] = designDelayMs (defer the course.json write, mirroring the
//                          research mock's delay knob for resume-banner
//                          tests that need a window on either side of the
//                          research → design boundary)
//
// Honours COURSES_ROOT_OVERRIDE so per-test tmpdirs work the same as the
// production courses/ root.

const fs = require('fs');
const path = require('path');

const slug = process.argv[2];
const designDelay = Number.parseInt(process.argv[3] ?? '0', 10) || 0;

if (!slug) {
  console.error('designCourse mock: missing argv[2] slug');
  process.exit(2);
}

const root = process.env.COURSES_ROOT_OVERRIDE || path.join(process.cwd(), 'courses');
const dir = path.join(root, slug);
fs.mkdirSync(path.join(dir, 'lessons'), { recursive: true });

console.log('[mock design_course] reading research.md + sources.md');

setTimeout(() => {
  console.log('[mock design_course] writing course.json');

  function slugify(input) {
    return String(input)
      .normalize('NFKD')
      .replace(/\p{M}/gu, '')
      .toLowerCase()
      .replace(/[_\s]+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
      .replace(/-+/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  let modules = [
    {
      id: 'm1',
      title: 'Module 1',
      summary: 'Stub module',
      lessons: [{ slug: 'intro', title: 'Intro', estimatedMinutes: 5 }],
    },
  ];
  let title = 'Mock Course';

  try {
    const specRaw = fs.readFileSync(path.join(dir, 'course-spec.json'), 'utf8');
    const spec = JSON.parse(specRaw);
    if (
      spec &&
      spec.draftStructure &&
      Array.isArray(spec.draftStructure.modules) &&
      spec.draftStructure.modules.length > 0
    ) {
      title = spec.draftStructure.courseTitle || title;
      const usedSlugs = new Set();
      modules = spec.draftStructure.modules.map((m, mi) => ({
        id: 'm' + (mi + 1),
        title: m.title,
        summary: 'Stub module',
        lessons: (m.lessons || []).map((l) => {
          let s = slugify(l.title) || 'lesson-' + (usedSlugs.size + 1);
          while (usedSlugs.has(s)) s = s + '-x';
          usedSlugs.add(s);
          return {
            slug: s,
            title: l.title,
            estimatedMinutes: l.estimatedMinutes || 5,
          };
        }),
      }));
    }
  } catch {
    // no spec — keep single-lesson default
  }

  const courseJson = {
    schemaVersion: 1,
    slug,
    title,
    description: 'Auto-generated by GENERATION_MOCK=1',
    accentColor: 'indigo',
    icon: 'sigma',
    modules,
    createdAt: '2026-05-04T00:00:00.000Z',
    updatedAt: '2026-05-04T00:00:00.000Z',
  };
  fs.writeFileSync(path.join(dir, 'course.json'), JSON.stringify(courseJson, null, 2));
  console.log('[mock design_course] done');
}, designDelay);
