// Mock claude -p stand-in for the generate_lesson stage. Writes a stub
// <coursesRoot>/<slug>/lessons/<lessonSlug>.json that validates against
// LessonSchema (one theory section, no AUTO_TTS sentinel — the TTS
// post-processor stays a no-op for this lesson).
//
// Spawned by defaultLessonCommand() when GENERATION_MOCK === '1'.
//
// argv[2] = slug         (already validated by assertSafeSlug before spawn)
// argv[3] = lessonSlug   (already validated by assertSafeSlug before spawn)
//
// Honours COURSES_ROOT_OVERRIDE so per-test tmpdirs work the same as the
// production courses/ root.

const fs = require('fs');
const path = require('path');

const slug = process.argv[2];
const lessonSlug = process.argv[3];

if (!slug || !lessonSlug) {
  console.error('generateLesson mock: requires argv[2]=slug and argv[3]=lessonSlug');
  process.exit(2);
}

const root = process.env.COURSES_ROOT_OVERRIDE || path.join(process.cwd(), 'courses');
const dir = path.join(root, slug, 'lessons');
fs.mkdirSync(dir, { recursive: true });

const lessonJson = {
  schemaVersion: 1,
  slug: lessonSlug,
  courseSlug: slug,
  moduleId: 'm1',
  title: lessonSlug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' '),
  eyebrow: 'MOCK',
  description: 'Stub lesson generated by GENERATION_MOCK=1.',
  estimatedMinutes: 5,
  sections: [
    {
      id: 's1',
      title: 'Read',
      type: 'theory',
      data: { markdown: 'Hello from the mock lesson generator.' },
    },
  ],
};

console.log(`[mock generate_lesson] writing ${lessonSlug}.json`);
fs.writeFileSync(
  path.join(dir, `${lessonSlug}.json`),
  JSON.stringify(lessonJson, null, 2),
);
console.log(`[mock generate_lesson] done ${lessonSlug}`);
