// Mock claude -p stand-in for the research_course stage. Writes minimal
// stub research.md + sources.md into <coursesRoot>/<slug>/. Neither file is
// schema-validated by the orchestrator, but both must exist for the
// post-research guard to pass and for the downstream design_course agent
// to have its inputs in place.
//
// Spawned by defaultResearchCourseCommand() when GENERATION_MOCK === '1'.
//
// argv[2] = slug             (already validated by assertSafeSlug before spawn)
// argv[3] = researchDelayMs  (deferring the artefact write keeps the run
//                             mid-flight long enough for the US-106 resume
//                             banner playwright test to navigate away + back)
//
// Honours COURSES_ROOT_OVERRIDE so per-test tmpdirs work the same as the
// production courses/ root.

const fs = require('fs');
const path = require('path');

const slug = process.argv[2];
const researchDelay = Number.parseInt(process.argv[3] ?? '0', 10) || 0;

if (!slug) {
  console.error('researchCourse mock: missing argv[2] slug');
  process.exit(2);
}

const root = process.env.COURSES_ROOT_OVERRIDE || path.join(process.cwd(), 'courses');
const dir = path.join(root, slug);
fs.mkdirSync(path.join(dir, 'lessons'), { recursive: true });

console.log('[mock research_course] researching topic...');

setTimeout(() => {
  console.log('[mock research_course] writing research.md');
  fs.writeFileSync(
    path.join(dir, 'research.md'),
    '# Research: Mock Course\n\n## Topic summary\n\nAuto-generated by GENERATION_MOCK=1.\n',
  );

  console.log('[mock research_course] writing sources.md');
  fs.writeFileSync(
    path.join(dir, 'sources.md'),
    '# Sources: Mock Course\n\n## Course-wide references\n\n- (none — mock fixture)\n',
  );

  console.log('[mock research_course] done');
}, researchDelay);
