import type { PlotImageData } from './schema';

export const SAMPLE_PLOT_IMAGE: PlotImageData = {
  src: '/api/courses/gauss-basics/assets/plots/example.png',
  alt: 'Example matplotlib plot with a sine curve',
  caption: 'Figure 1. A simple sinusoid generated by matplotlib.',
  sourceCode:
    "import numpy as np\nimport matplotlib.pyplot as plt\n\nx = np.linspace(0, 2 * np.pi, 200)\ny = np.sin(x)\nplt.plot(x, y)\nplt.savefig('example.png')\n",
  sourceLanguage: 'python',
};
