// Server-only module that owns the (single) running course-generation
// subprocess and exposes its output as a stream of structured events.
//
// Pipeline: `claude -p '/init_course <slug>' …` then `./scripts/ralph/ralph.sh`.
// Both child processes run with stdout+stderr captured to the run's event log
// AND tee'd to `/courses/<slug>/.generation.log`. Concurrency is gated to 1.

import {
  spawn as defaultSpawn,
  spawnSync,
  type ChildProcess,
  type SpawnOptions,
} from 'node:child_process';
import { promises as fs, createWriteStream, type WriteStream } from 'node:fs';
import path from 'node:path';
import { courseDir } from './paths';

export type GenerationEvent =
  | { type: 'log'; line: string }
  | { type: 'stage'; name: string; status: 'started' | 'done' | 'error' }
  | { type: 'progress'; current: number; total: number }
  | { type: 'done'; courseSlug: string }
  | { type: 'error'; message: string };

export type GenerationListener = (event: GenerationEvent) => void;

export interface GenerationRun {
  id: string;
  slug: string;
  events: GenerationEvent[];
  finished: boolean;
  subscribe: (listener: GenerationListener) => () => void;
  cancel: () => Promise<void>;
}

export interface SpawnDeps {
  spawn?: typeof defaultSpawn;
  isExecutableInPath?: (cmd: string) => boolean;
  initCourseCommand?: (slug: string) => { command: string; args: string[] };
  ralphCommand?: () => { command: string; args: string[] };
  cwd?: string;
  sigkillGraceMs?: number;
}

export class GenerationConflictError extends Error {
  constructor() {
    super('A generation is already running');
    this.name = 'GenerationConflictError';
  }
}

export class ClaudeUnavailableError extends Error {
  constructor() {
    super('Install Claude Code CLI or sign in to Claude Max');
    this.name = 'ClaudeUnavailableError';
  }
}

let activeRun: GenerationRun | null = null;
const runsById = new Map<string, GenerationRun>();
let depsOverride: SpawnDeps | null = null;

export function getActiveRun(): GenerationRun | null {
  return activeRun;
}

export function getRunById(id: string): GenerationRun | undefined {
  return runsById.get(id);
}

/** Test-only: replace global spawn deps for the next startGeneration calls. */
export function __setSpawnDepsForTesting(deps: SpawnDeps | null): void {
  depsOverride = deps;
}

/** Test-only: drop all bookkeeping and force-kill any active child. */
export function __resetForTesting(): void {
  if (activeRun && !activeRun.finished) {
    activeRun.finished = true;
  }
  activeRun = null;
  runsById.clear();
  depsOverride = null;
}

function defaultIsExecutableInPath(cmd: string): boolean {
  try {
    const result = spawnSync(process.platform === 'win32' ? 'where' : 'which', [cmd], {
      stdio: 'ignore',
    });
    return result.status === 0;
  } catch {
    return false;
  }
}

function defaultInitCourseCommand(slug: string): { command: string; args: string[] } {
  if (process.env.GENERATION_MOCK === '1') {
    // Test-only fast path that writes a valid stub course.json + lesson and
    // emits a few log lines. Lets the playwright browser test exercise the
    // full Stage-5-streaming → redirect-to-/courses/<slug> flow without
    // depending on a real `claude` CLI being on PATH.
    const courseJson = {
      schemaVersion: 1,
      slug,
      title: 'Mock Course',
      description: 'Auto-generated by GENERATION_MOCK=1',
      accentColor: 'indigo',
      icon: 'sigma',
      modules: [
        {
          id: 'm1',
          title: 'Module 1',
          summary: 'Stub module',
          lessons: [{ slug: 'intro', title: 'Intro', estimatedMinutes: 5 }],
        },
      ],
      createdAt: '2026-05-04T00:00:00.000Z',
      updatedAt: '2026-05-04T00:00:00.000Z',
    };
    const lessonJson = {
      schemaVersion: 1,
      slug: 'intro',
      courseSlug: slug,
      moduleId: 'm1',
      title: 'Intro',
      eyebrow: 'MOCK',
      description: 'Stub lesson generated for the browser test.',
      estimatedMinutes: 5,
      sections: [
        {
          id: 's1',
          title: 'Read',
          type: 'theory',
          data: { markdown: 'Hello from the mock generator.' },
        },
      ],
    };
    const script = `
const fs = require('fs');
const path = require('path');
const root = process.env.COURSES_ROOT_OVERRIDE || path.join(process.cwd(), 'courses');
const dir = path.join(root, ${JSON.stringify(slug)});
fs.mkdirSync(path.join(dir, 'lessons'), { recursive: true });
console.log('[mock init_course] researching topic...');
setTimeout(() => {
  console.log('[mock init_course] writing course.json');
  fs.writeFileSync(path.join(dir, 'course.json'), ${JSON.stringify(JSON.stringify(courseJson, null, 2))});
  fs.writeFileSync(path.join(dir, 'lessons', 'intro.json'), ${JSON.stringify(JSON.stringify(lessonJson, null, 2))});
  console.log('[mock init_course] done');
}, 200);
`;
    return { command: process.execPath, args: ['-e', script] };
  }
  return {
    command: 'claude',
    args: ['-p', `/init_course ${slug}`, '--dangerously-skip-permissions'],
  };
}

function defaultRalphCommand(): { command: string; args: string[] } {
  if (process.env.GENERATION_MOCK === '1') {
    const script = `
console.log('[mock ralph] starting');
setTimeout(() => {
  console.log('Lesson 1/1');
  setTimeout(() => {
    console.log('[mock ralph] all lessons generated');
  }, 100);
}, 200);
`;
    return { command: process.execPath, args: ['-e', script] };
  }
  return { command: './scripts/ralph/ralph.sh', args: [] };
}

function makeRunId(): string {
  return `gen-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

interface ChildSpec {
  command: string;
  args: string[];
}

export async function startGeneration(slug: string, depsArg: SpawnDeps = {}): Promise<GenerationRun> {
  const deps: SpawnDeps = { ...(depsOverride ?? {}), ...depsArg };

  if (activeRun && !activeRun.finished) {
    throw new GenerationConflictError();
  }

  const isExecutable = deps.isExecutableInPath ?? defaultIsExecutableInPath;
  if (!isExecutable('claude')) {
    throw new ClaudeUnavailableError();
  }

  const spawnFn = deps.spawn ?? defaultSpawn;
  const initSpec = (deps.initCourseCommand ?? defaultInitCourseCommand)(slug);
  const ralphSpec = (deps.ralphCommand ?? defaultRalphCommand)();
  const cwd = deps.cwd ?? process.cwd();
  const sigkillGraceMs = deps.sigkillGraceMs ?? 5000;

  const dir = courseDir(slug);
  await fs.mkdir(dir, { recursive: true });
  const logPath = path.join(dir, '.generation.log');
  const logStream: WriteStream = createWriteStream(logPath, { flags: 'w' });
  let logStreamClosed = false;
  // Swallow late "write after end" errors that can fire when a child's stdout
  // flushes one more chunk after we've already finalised the run.
  logStream.on('error', () => {
    /* no-op */
  });

  const id = makeRunId();
  const events: GenerationEvent[] = [];
  const listeners = new Set<GenerationListener>();
  let cancelled = false;
  let currentChild: ChildProcess | null = null;
  let killTimer: NodeJS.Timeout | null = null;

  const run: GenerationRun = {
    id,
    slug,
    events,
    finished: false,
    subscribe(listener) {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
    async cancel() {
      if (run.finished) return;
      cancelled = true;
      const child = currentChild;
      if (!child || child.exitCode !== null) return;
      try {
        child.kill('SIGTERM');
      } catch {
        /* ignore */
      }
      if (!killTimer) {
        killTimer = setTimeout(() => {
          try {
            child.kill('SIGKILL');
          } catch {
            /* ignore */
          }
        }, sigkillGraceMs);
        // Don't keep the event loop alive just for the kill timer.
        if (typeof killTimer.unref === 'function') killTimer.unref();
      }
    },
  };

  function emit(event: GenerationEvent) {
    events.push(event);
    for (const listener of [...listeners]) {
      try {
        listener(event);
      } catch {
        /* listeners are isolated */
      }
    }
  }

  function tryParseProgress(line: string) {
    // Recognise "Lesson 3/12", "Generated lesson 3 of 12", "(2/5)", etc.
    const slash = /(?:^|[^0-9])(\d+)\s*\/\s*(\d+)(?:[^0-9]|$)/;
    const ofWord = /(\d+)\s+of\s+(\d+)/i;
    const match = line.match(slash) ?? line.match(ofWord);
    if (!match) return;
    const current = parseInt(match[1], 10);
    const total = parseInt(match[2], 10);
    if (!Number.isFinite(current) || !Number.isFinite(total)) return;
    if (total <= 0 || current < 0 || current > total) return;
    emit({ type: 'progress', current, total });
  }

  function pumpStream(child: ChildProcess) {
    let stdoutBuf = '';
    let stderrBuf = '';

    const flushLine = (line: string) => {
      if (line.length === 0 && !stdoutBuf && !stderrBuf) return;
      if (!logStreamClosed) {
        try {
          logStream.write(`${line}\n`);
        } catch {
          /* log file already closed — fall through */
        }
      }
      emit({ type: 'log', line });
      tryParseProgress(line);
    };

    const pump = (which: 'out' | 'err') => (chunk: Buffer | string) => {
      const text = typeof chunk === 'string' ? chunk : chunk.toString('utf8');
      if (which === 'out') {
        stdoutBuf += text;
        let idx;
        while ((idx = stdoutBuf.indexOf('\n')) !== -1) {
          const line = stdoutBuf.slice(0, idx).replace(/\r$/, '');
          stdoutBuf = stdoutBuf.slice(idx + 1);
          flushLine(line);
        }
      } else {
        stderrBuf += text;
        let idx;
        while ((idx = stderrBuf.indexOf('\n')) !== -1) {
          const line = stderrBuf.slice(0, idx).replace(/\r$/, '');
          stderrBuf = stderrBuf.slice(idx + 1);
          flushLine(line);
        }
      }
    };

    child.stdout?.on('data', pump('out'));
    child.stderr?.on('data', pump('err'));
    child.once('close', () => {
      // Flush partial trailing lines so nothing is dropped on exit.
      if (stdoutBuf.length > 0) {
        flushLine(stdoutBuf.replace(/\r$/, ''));
        stdoutBuf = '';
      }
      if (stderrBuf.length > 0) {
        flushLine(stderrBuf.replace(/\r$/, ''));
        stderrBuf = '';
      }
    });
  }

  function spawnStage(name: string, spec: ChildSpec): Promise<{ exit: number }> {
    return new Promise((resolve) => {
      emit({ type: 'stage', name, status: 'started' });
      const opts: SpawnOptions = {
        cwd,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: process.env,
      };
      let child: ChildProcess;
      try {
        child = spawnFn(spec.command, spec.args, opts);
      } catch (err) {
        emit({ type: 'log', line: `spawn failed for ${spec.command}: ${(err as Error).message}` });
        resolve({ exit: -1 });
        return;
      }
      currentChild = child;
      pumpStream(child);
      let exitCode: number | null = null;
      child.once('error', (err) => {
        emit({ type: 'log', line: `${name} error: ${err.message}` });
      });
      child.once('exit', (code) => {
        exitCode = code;
      });
      // Use 'close' (not 'exit'): in Node child_process, 'close' fires after
      // stdio streams have been fully drained, so all data events for this
      // child have already been delivered. Resolving on 'exit' would race
      // with pending stdout chunks that arrive on a later tick.
      child.once('close', (code) => {
        if (killTimer) {
          clearTimeout(killTimer);
          killTimer = null;
        }
        currentChild = null;
        resolve({ exit: (exitCode ?? code) ?? -1 });
      });
    });
  }

  function finalize(kind: 'done' | 'error', message?: string) {
    if (run.finished) return;
    run.finished = true;
    if (killTimer) {
      clearTimeout(killTimer);
      killTimer = null;
    }
    if (kind === 'done') {
      emit({ type: 'done', courseSlug: slug });
    } else {
      emit({ type: 'error', message: message ?? 'Generation failed' });
    }
    logStreamClosed = true;
    try {
      logStream.end();
    } catch {
      /* ignore */
    }
    if (activeRun === run) activeRun = null;
  }

  activeRun = run;
  runsById.set(id, run);

  const pipeline = (async () => {
    const initResult = await spawnStage('init_course', initSpec);
    if (cancelled) {
      emit({ type: 'stage', name: 'init_course', status: 'error' });
      finalize('error', 'Cancelled by user');
      return;
    }
    if (initResult.exit !== 0) {
      emit({ type: 'stage', name: 'init_course', status: 'error' });
      finalize('error', `init_course failed (exit ${initResult.exit})`);
      return;
    }
    emit({ type: 'stage', name: 'init_course', status: 'done' });

    const ralphResult = await spawnStage('ralph', ralphSpec);
    if (cancelled) {
      emit({ type: 'stage', name: 'ralph', status: 'error' });
      finalize('error', 'Cancelled by user');
      return;
    }
    if (ralphResult.exit !== 0) {
      emit({ type: 'stage', name: 'ralph', status: 'error' });
      finalize('error', `ralph failed (exit ${ralphResult.exit})`);
      return;
    }
    emit({ type: 'stage', name: 'ralph', status: 'done' });
    finalize('done');
  })();

  pipeline.catch((err) => {
    finalize('error', err instanceof Error ? err.message : String(err));
  });

  return run;
}

export function sseEncode(event: GenerationEvent): Uint8Array {
  return new TextEncoder().encode(`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`);
}
